name: typing
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  number_ticker: ^0.0.2+1
  path_provider: ^2.0.8
  show_up_animation: ^2.0.0
  google_fonts: ^2.2.0
  shared_preferences: ^2.0.12
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.1
  bitsdojo_window: ^0.1.1+1
  simple_tip: ^0.3.2
  side_navigation: ^0.0.7
  fl_chart: ^0.41.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/p/
